### ISSUE TITLE
A source repo must be provided to validate other rules

### ISSUE THREAD

**Issue by cwebberOps** [chef-cookbooks/cookbook-quality-metrics-rfc#12]
So I am not sure how this actually maps to a rule, but I figured I would put down the thoughts as an issue.

In reality, many of the things we think of as adding quality to a cookbook are not necessarily present in the artifact that gets uploaded to Supermarket. The best known of these is the `metadata.rb` file. While we could get into arguments about that specific issue, it doesn't change the fact that things like `.kitchen.yml` files, specs, etc. probably shouldn't be in the final artifact. As a result we need to look at a source repo.

Additionally, it is important to recognize that while many of us use GitHub, it is not the only source for a cookbook. It is completely reasonable that it could come off GitLab or BitBucket. It just needs to be accessible for us to grab it and run tests against it.

In the same vein, it is probably reasonable, at least at first, to only accept a git remote. But yeah...

I struggle to assign points one way or the other on this because it becomes a prerequisite for so many other things. Like who cares if it is worth 100 points if you cant earn any of the linting, rspec, etc points?

Whether this is implicit or explicit doesn't really matter to me, but having started down the path of thinking about cookbook metrics, through things like Fieri, this is going to be super important.

**Comment by martinb3** [comment]
Additionally, we may find cookbooks that require additional gems to run certain rake tasks, as this is commonly used to provide additional functionality like the ability to run chef-sugar inside chefspec or to provide additional foodcritic rules. I think we'll need to figure out some sort of policy around what we will and won't support if we're actually running spec tests or any custom linting like rubocop/foodcritic.

**Comment by nathenharvey** [comment]
We have a metric for this [009-Source-URL](https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/quality-metrics/qm-009-source-url.md)

The reality is that we will need to access that source url via some API integration point to measure some other metrics.  We'd probably start with GitHub as that is most likely the most popular.

We have had a number of recent debates about what should be published to the Supermarket and I expect we'll see an RFC and/or discussion at the Community Summit around this topic,
