### ISSUE TITLE
A mechanisim for announcing that the rules have changed

### ISSUE THREAD

**Issue by nathenharvey** [chef-cookbooks/cookbook-quality-metrics-rfc#13]
We need a process for announcing changes to the game.  Specifically:
- A new rule is added
- A rule is removed

**Comment by martinb3** [comment]
Perhaps rulesets could have a version, or be tied to a particular chef version.

**Comment by iennae** [comment]
Hey folks, we should circle back to this since we've got some of the quality metrics enabled on Supermarket now. Any new thoughts since this issue was created?

**Comment by iennae** [comment]
We plan to discuss this on the developer meeting on March 2, 2017 https://github.com/chef/chef-community-slack-meetings/blob/master/2017-03-02-agenda.md. Meetings are held in the Chef Community slack in the #developer-meetings channel: https://github.com/chef/chef-rfc/blob/master/rfc001-slack-meetings.md.

**Comment by nathenharvey** [comment]
The [SMQM.md](https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/SMQM.md) file lists the current status of each rule and rules have been included in [Supermarket Release Announcements](https://discourse.chef.io/t/supermarket-2-9-3-released/10350) where applicable.

**Comment by iennae** [comment]
Based on discussions in the developer meeting on March 2, 2017 [2017-03-02-minutes.md](https://github.com/chef/chef-community-slack-meetings/blob/master/2017/2017-03-02/2017-03-02-minutes.md), the github information provided in [SMQM.md](https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/SMQM.md) file and the process of announcing in Supermarket release announcements are sufficient mechanisms. A separate issue will be raised on documenting cookbook quality metrics on the docs site or Supermarket outside of github.
