### ISSUE TITLE
There should be a way to view the points for all rules in one view

### ISSUE THREAD

**Issue by mwrock** [chef-cookbooks/cookbook-quality-metrics-rfc#14]
Its hard to understand the point impact of a single rule without being able to view its points (given and taken) in relationship to the other rules. I'd propose both a CLI command and a supermarket web page that can list all rules in a grid-like format with their point additions and deductions.

**Comment by nathenharvey** [comment]
:+1: in the meantime, maybe a simple markdown file that shows this so you can have an easy aggregate view would be helpful?  It could be updated as part of the merge process

**Comment by mwrock** [comment]
that works

**Comment by nathenharvey** [comment]
See [SMQM.md](https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/SMQM.md) as a start of this.  This shall be manually updated by the editors when merging in new rules (at least for now).
