### ISSUE TITLE
Maintainer email address

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/cookbook-quality-metrics-rfc#37]
We have merged this rule, but I don't see an actual public way to validate if an email address exists for the maintainer:
https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/quality-metrics/qm-006-maintainer_email.md

It appears that, since Supermarket accounts go through Chef's federated auth, email addresses are only stored there, and aren't published.

Should we remove this metric? Or adjust to be "github account with email"?

**Comment by martinb3** [comment]
`004    Cookbook has collaborators on the Supermarket` has a similar issue, where it doesn't appear to be available in the RESTful API, even though it does get exposed in the browser for Supermarket visitors.

**Comment by tas50** [comment]
At the moment we're not worried about how we'll go about validating these metrics.  We're more concerned with coming up with a quality list of metrics outside of the technical implementation.  Once we move to the implementation phase we'll have to look at the changes to supermarket and chef itself to make some of these possible.

**Comment by martinb3** [comment]
@tas50 :+1: thanks for the context. Maybe we could note that on the documentation to make it clear for readers and then I'll close this :)

**Comment by martinb3** [comment]
Submitted #38 to clarify this in the readme.
